### ISSUE TITLE
code block

### ISSUE THREAD

**Issue by arch-spatula** [arch-spatula/arch-spatula.github.io#10]
- [x] 텍스 모노스페이스
- [x] 복사 버튼 추가
- [x] 테마 지정

**Comment by arch-spatula** [comment]
https://www.youtube.com/watch?v=_0eBQREJTDo

**Comment by arch-spatula** [comment]
텍스트 모노스페이스

```css
  .astro-code {
    padding: 1rem;
    border-radius: 1rem;
    margin: 2rem 0 1rem;
  }

  .astro-code > code > .line > span {
    font-family: "Menlo", "Monaco", "Courier New", monospace !important;
  }
```
